### ISSUE TITLE
想把这个插件加入到真寻bot的适配列表里

### ISSUE THREAD

**Issue by SinKy-Yan** [Josef1999/ApexLegends-QQ-Robot#1]
你好，那个
我fork了你的这个仓库并且改了些东西让它适配[真寻bot](https://github.com/HibiKier/zhenxun_bot)
然后我现在想把它加入到[真寻bot的插件库](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/tree/index)里，想问下行不行
或者合并到你的仓库的主分支上？
https://github.com/SinKy-Yan/ApexLegends-QQ-Robot

**Comment by Josef1999** [comment]
可以的，注明一下出处就行
如果希望合并到主分支上的话可以提个pull request

**Comment by Josef1999** [comment]
已merge至主分支

**Comment by SinKy-Yan** [comment]
已经给bot插件列表提交pr了
https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/pull/62
