### ISSUE TITLE
安装依赖项出错

### ISSUE THREAD

**Issue by dongbao66** [Josef1999/ApexLegends-QQ-Robot#13]
![QQ图片20220530205908](https://user-images.githubusercontent.com/95880227/170997466-cfd45669-479d-4b4f-a3c2-40e0d71ab4cb.png)

**Comment by Josef1999** [comment]
抱歉，requirements里我多加了json，最新版的已经去掉了

**Comment by dongbao666666** [comment]
![image](https://user-images.githubusercontent.com/95880227/170999021-eb42539d-91a5-4239-8701-be62e4978c44.png)
重新安装依赖，这个报错?

**Comment by dongbao66** [comment]
> 抱歉，requirements里我多加了json，最新版的已经去掉了

![image](https://user-images.githubusercontent.com/95880227/170999508-4691e4fd-bb73-47c4-95d9-a530ea0fc8cd.png)
又报错

**Comment by Josef1999** [comment]
这不是本插件的依赖吧？

**Comment by dongbao66** [comment]
> 这不是本插件的依赖吧？

![image](https://user-images.githubusercontent.com/95880227/171000115-c39f5a92-4e05-46f2-b003-4e41f9b9b92a.png)
我重新下载的安装包 就输入了 pip3 install -r requirements.txt

**Comment by Josef1999** [comment]
Python版本是多少？NoneBot2 仅支持 Python 3.7.3 以上版本

**Comment by dongbao66** [comment]
> Python版本是多少？NoneBot2 仅支持 Python 3.7.3 以上版本
3.9版本

![image](https://user-images.githubusercontent.com/95880227/171002937-e6f920dd-3dd7-4575-97cf-2196ea0005dd.png)

**Comment by Josef1999** [comment]
那就是包冲突了，starlette这个包和你已有的包冲突

**Comment by dongbao66** [comment]
> 那就是包冲突了，starlette这个包和你已有的包冲突

淦 这怎么搞 我还不知道那个包冲突了

**Comment by Josef1999** [comment]
我也无能为力

**Comment by dongbao66** [comment]
> 我也无能为力

重试了一遍，又能全部安装好了
运行bot。py  报错
![image](https://user-images.githubusercontent.com/95880227/171007711-dc9167b9-4585-4ccf-ab5a-2880f14ea8aa.png)

**Comment by Josef1999** [comment]
requests库没有安装，你是通过pip install -r requirements命令安装的依赖吗？理论上不会漏安装requests阿
