### ISSUE TITLE
插件的加载出现

### ISSUE THREAD

**Issue by 15220526** [Josef1999/ApexLegends-QQ-Robot#3]
插件在加载的时候出现了以下的报错这是哪里出现了问题呢
![image](https://user-images.githubusercontent.com/106159640/170418330-ada571b0-61bf-46d1-815c-2952eeda25ab.png)

**Comment by Josef1999** [comment]
看报错信息是因为读取config.json中json时有无效的斜杠（\），试试看去除末尾的斜杠？
![image](https://user-images.githubusercontent.com/43344888/170419909-0ffdde35-0c36-4a71-aa8a-a71ab5e46756.png)

**Comment by 15220526** [comment]
在改完这个之后又有新的问题，在输入查询战绩的时候跳出了报错
![image](https://user-images.githubusercontent.com/106159640/170422836-3ade25bd-8be5-43b3-a954-a326bf5497ed.png)

**Comment by Josef1999** [comment]
更新了代码，试下重新下载插件
错误原因是qq_eaID.json文件的路径未知，修改了路径查找的相关逻辑

**Comment by 15220526** [comment]
在输入地图信息的时候出现了报错，这个报错之后查询信息和绑定ID都变得没有反应
![O5}~UJC $SPPD N `3FHW~V](https://user-images.githubusercontent.com/106159640/170429040-39778745-cbc6-4982-8f0a-861e07a28f18.png)
![BGK_7%V7A`CU%HDPJ6$XBXR](https://user-images.githubusercontent.com/106159640/170429063-ac892cbb-8526-437b-afd5-d2c8b4bddb33.png)

**Comment by 15220526** [comment]
输入地图信息的时候出现了报错，在这个报错之后查询战绩和绑定id都变得没有反应。
![O5}~UJC $SPPD N `3FHW~V](https://user-images.githubusercontent.com/106159640/170429696-6136e58f-407d-40ec-a6a1-0fd0fa8ab2f9.png)

![BGK_7%V7A`CU%HDPJ6$XBXR](https://user-images.githubusercontent.com/106159640/170429719-f7b192e6-1d2d-4c3c-b49c-66bf22f6abb9.png)

**Comment by Josef1999** [comment]
看报错信息是因为相关查询网站未响应，推测可能是需要使用自己生成的API KEY？
api key 在https://portal.apexlegendsapi.com/ 生成

**Comment by 15220526** [comment]
我这边已经是换成自己生成的api key了但是还是报错且其他的指令还是没有反应
![image](https://user-images.githubusercontent.com/106159640/170480697-ccc8571e-b985-4b37-83e9-cac347564c60.png)

**Comment by Josef1999** [comment]
请问有使用代理吗？

**Comment by 15220526** [comment]
有

**Comment by Josef1999** [comment]
试试看关闭代理？我搜到一个类似案例https://blog.csdn.net/u010182162/article/details/123329862，似乎是和代理有关

**Comment by 15220526** [comment]
嗯地图信息可以查询了，但是其他的三项账号绑定、复制器信息还有战绩查询都是无法使用的，输入指令只有没有反应。
![image](https://user-images.githubusercontent.com/106159640/170482690-43cc975d-be0a-4b7b-9820-6a314fe3444a.png)

**Comment by Josef1999** [comment]
指令输入有误，可以先更新下插件，然后看下指令说明
