### ISSUE TITLE
希望有JJC和猎杀底分

### ISSUE THREAD

**Issue by ayakasuki** [Josef1999/ApexLegends-QQ-Robot#4]
要求可能有点无理
但还是不情之请，，
最好还带点图片——谢谢大佬，love.

**Comment by Josef1999** [comment]
抱歉，目前的查询功能都是基于https://apexlegendsapi.com/ 提供的api做的，实现这些需求需要对应的api，如果找到了我就能升级插件的功能

**Comment by ayakasuki** [comment]
谢谢Josef

**Comment by Josef1999** [comment]
😊也谢谢你的建议

**Comment by quanquan1014** [comment]
> 抱歉，目前的查询功能都是基于https://apexlegendsapi.com/提供的api做的，实现需要api，如果找到了我的升级插件的功能
也许可以用这个api
https://tracker.gg/developers/docs/titles/apex

**Comment by Josef1999** [comment]
谢谢，我会看下的

**Comment by Josef1999** [comment]
> > 抱歉，目前的查询功能都是基于[https://apexlegendsapi.com/提供的api做的，实现需要api，如果找到了我的升级插件的功能](https://apexlegendsapi.com/%E6%8F%90%E4%BE%9B%E7%9A%84api%E5%81%9A%E7%9A%84%EF%BC%8C%E5%AE%9E%E7%8E%B0%E9%9C%80%E8%A6%81api%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%89%BE%E5%88%B0%E4%BA%86%E6%88%91%E7%9A%84%E5%8D%87%E7%BA%A7%E6%8F%92%E4%BB%B6%E7%9A%84%E5%8A%9F%E8%83%BD)
> > 也许可以用这个api
> > https://tracker.gg/developers/docs/titles/apex

看了下似乎用不了，这些api是针对它的app使用的，需要相应app鉴权
