### ISSUE TITLE
windows下绑定id无反应

### ISSUE THREAD

**Issue by willater** [Josef1999/ApexLegends-QQ-Robot#6]
输入绑定id，会提示"请输入EA ID!",再输入id后无反应，后台无报错
后台：

![image](https://user-images.githubusercontent.com/60524164/170450672-8a63c82c-0612-45f0-a8c0-ecca5bfc2b49.png)

debug日志(抹去了群号和qq号)：

05-26 16:20:48 [SUCCESS] nonebot | ONEBOT V11 1573575604 | [message.group.normal]: Message 1628533322 from xxxxxxxx@[群:xxxxxxxx] "绑定id"
05-26 16:20:48 [DEBUG] nonebot | Checking for matchers in priority 1...
05-26 16:20:48 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-26 16:20:48 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:48 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:48 [INFO] nonebot | Event will be handled by <Matcher from plugins.ApexLegends_QQ_Robot_master, type=message, priority=1, temp=False>
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:48 [DEBUG] nonebot | Running matcher <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-26 16:20:48 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x00000205AB544A60>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='event', type=GroupMessageEvent, required=True)], parameterless=[]>
05-26 16:20:48 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-26 16:20:48 [DEBUG] nonebot | Running matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-26 16:20:48 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-26 16:20:48 [DEBUG] nonebot | Running matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-26 16:20:48 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x00000205A5B523A0>, params=[ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
05-26 16:20:48 [DEBUG] nonebot | Running matcher <Matcher from plugins.ApexLegends_QQ_Robot_master, type=message, priority=1, temp=False>
05-26 16:20:48 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x00000205ACC30E50>, params=[ModelField(name='event', type=Event, required=True), ModelField(name='text', type=Message, required=True)], parameterless=[]>
05-26 16:20:48 [DEBUG] nonebot | Running CallingAPI hooks...
05-26 16:20:48 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
05-26 16:20:48 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-26 16:20:48 [INFO] nonebot | Matcher <Matcher from plugins.ApexLegends_QQ_Robot_master, type=message, priority=1, temp=False> running complete
05-26 16:20:48 [DEBUG] nonebot | Checking for matchers in priority 4...
05-26 16:20:48 [DEBUG] nonebot | Checking for matchers in priority 5...
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:48 [DEBUG] nonebot | Checking for matchers in priority 6...
05-26 16:20:48 [DEBUG] nonebot | Checking for matchers in priority 7...
05-26 16:20:48 [DEBUG] nonebot | Checking for matchers in priority 9...
05-26 16:20:48 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False>
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:48 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:48 [DEBUG] nonebot | Running matcher <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False>
05-26 16:20:48 [INFO] nonebot | Matcher <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False> running complete
05-26 16:20:48 [DEBUG] nonebot | Checking for matchers in priority 13...
05-26 16:20:48 [DEBUG] nonebot | Checking for matchers in priority 15...
05-26 16:20:48 [DEBUG] nonebot | Checking for matchers in priority 998...
05-26 16:20:49 [DEBUG] nonebot | Checking for matchers in priority 999...
05-26 16:20:49 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False>
05-26 16:20:49 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:49 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:49 [INFO] nonebot | Event will be handled by <Matcher from plugins.fudu, type=message, priority=999, temp=False>
05-26 16:20:49 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:49 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:49 [DEBUG] nonebot | Running matcher <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False>
05-26 16:20:49 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x00000205A575F820>, params=[ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
05-26 16:20:49 [DEBUG] nonebot | Running matcher <Matcher from plugins.fudu, type=message, priority=999, temp=False>
05-26 16:20:49 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x00000205AC254E50>, params=[ModelField(name='event', type=GroupMessageEvent, required=True)], parameterless=[]>
05-26 16:20:49 [INFO] nonebot | Matcher <Matcher from plugins.fudu, type=message, priority=999, temp=False> running complete
05-26 16:20:49 [INFO] nonebot | Matcher <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False> running complete
05-26 16:20:49 [DEBUG] nonebot | Stop event propagation
05-26 16:20:51 [SUCCESS] nonebot | ONEBOT V11 1573575604 | [message.group.normal]: Message -1893788826 from xxxxxxxxx@[ 群:xxxxxxxxx] "kokoiro_koiro"
05-26 16:20:51 [DEBUG] nonebot | Checking for matchers in priority 1...
05-26 16:20:51 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-26 16:20:51 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-26 16:20:51 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:51 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:51 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:51 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:52 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-26 16:20:52 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:52 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:52 [DEBUG] nonebot | Running matcher <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-26 16:20:52 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x00000205AB544A60>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='event', type=GroupMessageEvent, required=True)], parameterless=[]>
05-26 16:20:52 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-26 16:20:52 [DEBUG] nonebot | Running matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-26 16:20:52 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-26 16:20:52 [DEBUG] nonebot | Running matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-26 16:20:52 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x00000205A5B523A0>, params=[ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
05-26 16:20:52 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-26 16:20:52 [DEBUG] nonebot | Checking for matchers in priority 4...
05-26 16:20:52 [DEBUG] nonebot | Checking for matchers in priority 5...
05-26 16:20:52 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B68E50> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B68F70> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7C0D0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7C1F0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7C310> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7C430> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7C550> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7C670> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7C790> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7C8B0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7C9D0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7CAF0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7CC10> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7CD30> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7CE50> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3B7CF70> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE00D0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE01F0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE0310> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE0430> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE04C0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE0670> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE0790> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE08B0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE09D0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE0AF0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE0C10> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE0D30> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE0E50> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3BE0F70> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3E0D0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3E1F0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3E280> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3E430> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3E550> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3E5E0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3E790> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3E8B0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3E9D0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3EAF0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3EC10> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3ED30> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3EE50> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C3EF70> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9A0D0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9A160> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9A310> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9A430> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9A550> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9A670> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9A790> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9A820> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9A9D0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9AAF0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9AC10> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9AD30> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9AE50> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3C9AF70> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3CFD0D0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3CFD1F0> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3CFD280> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3CFD430> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function check_args_rule.<locals>.check_args at 0x00000205B3CFD550> annotation Message, ignored
05-26 16:20:52 [DEBUG] nonebot | Checking for matchers in priority 6...
05-26 16:20:52 [DEBUG] nonebot | Checking for matchers in priority 7...
05-26 16:20:52 [DEBUG] nonebot | Checking for matchers in priority 9...
05-26 16:20:52 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False>
05-26 16:20:52 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:52 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:52 [DEBUG] nonebot | Running matcher <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False>
05-26 16:20:52 [INFO] nonebot | Matcher <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False> running complete
05-26 16:20:52 [DEBUG] nonebot | Checking for matchers in priority 13...
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function smart_to_me at 0x00000205ADA7B160> annotation Tuple[str, ...], ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function smart_to_me at 0x00000205ADA7B160> annotation Tuple[str, ...], ignored
05-26 16:20:52 [DEBUG] nonebot |  type <class 'NoneType'> not match depends <function smart_to_me at 0x00000205ADA7B160> annotation Tuple[str, ...], ignored
05-26 16:20:52 [DEBUG] nonebot | Checking for matchers in priority 15...
05-26 16:20:52 [DEBUG] nonebot | Checking for matchers in priority 998...
05-26 16:20:52 [DEBUG] nonebot | Checking for matchers in priority 999...
05-26 16:20:52 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False>
05-26 16:20:52 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:52 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:52 [INFO] nonebot | Event will be handled by <Matcher from plugins.fudu, type=message, priority=999, temp=False>
05-26 16:20:52 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
05-26 16:20:52 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PokeNotifyEvent, ignored
05-26 16:20:52 [DEBUG] nonebot | Running matcher <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False>
05-26 16:20:52 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x00000205A575F820>, params=[ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
05-26 16:20:52 [DEBUG] nonebot | Running matcher <Matcher from plugins.fudu, type=message, priority=999, temp=False>
05-26 16:20:52 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x00000205AC254E50>, params=[ModelField(name='event', type=GroupMessageEvent, required=True)], parameterless=[]>
05-26 16:20:52 [INFO] nonebot | Matcher <Matcher from plugins.fudu, type=message, priority=999, temp=False> running complete
05-26 16:20:52 [INFO] nonebot | Matcher <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False> running complete
05-26 16:20:52 [DEBUG] nonebot | Stop event propagation

**Comment by willater** [comment]
现在插件的目录是在plugins里，不是自定目录了

**Comment by Josef1999** [comment]
抱歉，传参提示有误，应该是".绑定id EA_ID"这样的格式，不是先调用命令再输入ea id

**Comment by willater** [comment]
好的！我再试试！

**Comment by willater** [comment]
现在可以绑定或者查询战绩了，不过绑定或者查询经常出现这种问题，请问这种问题是网络问题嘛？
![image](https://user-images.githubusercontent.com/60524164/170455292-5afcae80-4a6a-4c5e-88cc-9fcaea37854f.png)
![image](https://user-images.githubusercontent.com/60524164/170455366-6077ce54-9379-4047-9a57-1451b9e2eb56.png)
![image](https://user-images.githubusercontent.com/60524164/170455390-1ce72b47-e8da-4fd5-97b2-46c0f324e902.png)

**Comment by Josef1999** [comment]
是的，有将config.json中的APEX_AUTH更新为自己的api key吗？理论上每个api key每分钟可以查30次

**Comment by willater** [comment]
有的，现在就是偶尔可以偶尔不行，不知道为啥，开关代理效果都一样

**Comment by Josef1999** [comment]
代理应该不影响，你的查询频率高吗？https://apexlegendsapi.com/ 上可以升级查询频率到一分钟120次，可以试试。如果还不行的话说明是这个网站不稳定

**Comment by SinKy-Yan** [comment]
看报错确实是跟网站连接超时，试试更换一个DNS服务器，有可能是DNS超时导致解析不到IP
最好顺便试试不用插件能不能ping通

**Comment by willater** [comment]
频率最多五六秒一次，频率上肯定没问题

**Comment by willater** [comment]
我试试换个dns
